apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    build: CodeMagic Testing
espresso:
  app: app/build/outputs/app.apk
  testApp: app/build/app-androidTest.apk
suites:
  - name: "Android Emulator"
    emulators:
      - name: "Android GoogleAPI Emulator"
        platformVersions:
          - "12.0"
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
